---
name: Metrics
on:
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Header
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.header.svg
          base: repositories, metadata
          base_hireable: yes
          base_indepth: yes
          config_timezone: Asia/Taipei
          config_twemoji: yes

      - name: Generate Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.languages.svg
          base: ""
          config_timezone: Asia/Taipei
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: html, css, jupyter notebook
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used, other-langs 
          plugin_languages_threshold: 0.1%
